In [1]:
from gldata_fx.mc_fx import split_english,get_fds,mcfy,get_schema
from kwpb import kwpb
from config_1 import Config
import json
kwpb = kwpb()

2023-05-15 11:17:31.932 | DEBUG    | text2vec.sentence_model:__init__:74 - Use device: cpu


In [2]:
with open("/home/tzy/Classification/datas/gl_dbs.json", encoding='utf-8') as fp1:
    a = json.load(fp1)
with open("/home/tzy/Classification/datas/cihsy.json", encoding='utf-8') as fp1:
    cihsy = json.load(fp1)

In [3]:
fds = list(set(get_fds(a)))

In [2]:
cnf = Config()
# dd = fds[:9]
# dd

In [3]:
dd = [
    {'field_name':'asdwq','field_description':'adsaaaaaaa。aaaaaaaaa'},
    {'field_name':'sfd','field_description':''},
    {'field_name':'sfd','field_description':'eeeeee'},
    {'field_name':'auyksdwq','field_description':'eqrerrt。啊大师傅。jjdsfs'}
    ]
res = kwpb.get_res(cnf.mgkey_dic,dd)
res #print(slys, indx, n1, v1, v2)

/home/tzy/Classification/kwpb.py:108: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  left = left+((right-left)//(nn[right]-nn[left]))*(x-nn[left])+1


[('身份证号码', tensor(0.6226), 'sfzh', 'aaaaaaaaa'),
 ('密码', tensor(0.6899), 'pwd', 'sfd'),
 ('密码', tensor(0.6899), 'pwd', 'sfd'),
 ('身份证号码', tensor(0.7822), 'sfzh', 'jjdsfs')]

In [6]:
for i in res:
    if i[1]>0.9:
        print(i)

In [4]:
ss = kwpb.sim_model.similarity(['pwd'], ['sfd'])
ss

tensor([[0.6899]])

In [11]:
ss = kwpb.sim_model.similarity(['MilitaryID','ew'], ['OperationFlag','sdfds','aas'])
ss

tensor([[0.4574, 0.3555, 0.4293],
        [0.4176, 0.4584, 0.8097]])

In [13]:
import torch
sys,inx = torch.max(ss,1)

In [14]:
inx

tensor([0, 2])